package seed

var fakeNames = []string{
	"James", "Mary", "Robert", "Patricia", "John", "Jennifer", "Michael", "Linda",
	"William", "Elizabeth", "David", "Barbara", "Richard", "Susan", "Joseph", "Jessica",
	"Thomas", "Sarah", "Charles", "Karen", "Christopher", "Nancy", "Daniel", "Lisa",
	"Matthew", "Betty", "Anthony", "Margaret", "Mark", "Sandra", "Donald", "Ashley",
	"Paul", "Kimberly", "Steven", "Emily", "Andrew", "Donna", "Kenneth", "Michelle",
	"Joshua", "Dorothy", "George", "Carol", "Kevin", "Amanda", "Brian", "Melissa",
	"Edward", "Deborah",
}

var fakePostsNames = []string{
	"10 Tips for a Productive Morning",
	"How to Start Your Own Business in 2024",
	"The Ultimate Guide to Remote Work",
	"Top 5 Travel Destinations for Adventure Lovers",
	"Simple Recipes for Healthy Eating",
	"The Science Behind Better Sleep",
	"Building Better Habits: A Step-by-Step Approach",
	"Why You Should Learn a New Skill This Year",
	"How to Save Money on Everyday Expenses",
	"Top 10 Apps for Staying Organized",
	"Overcoming Fear: Tips for Personal Growth",
	"The Future of Artificial Intelligence",
	"How to Write an Engaging Blog Post",
	"Mastering Time Management for Success",
	"Fitness Hacks for Busy Professionals",
	"5 Strategies for Building Self-Confidence",
	"The Benefits of Minimalist Living",
	"How to Build a Stronger Network",
	"Top 7 Books for Personal Development",
	"The Secrets to Effective Communication",
	"How to Stay Motivated While Working from Home",
	"Tips for Reducing Stress in Daily Life",
	"Travel Hacks You Need to Know",
	"How to Start a Podcast from Scratch",
	"The Importance of Financial Literacy",
	"Creating a Morning Routine That Works for You",
	"How to Plan the Perfect Vacation",
	"The Benefits of Journaling for Mental Clarity",
	"Top Trends in Technology for 2024",
	"How to Be More Productive Without Burning Out",
	"5 Easy Ways to Improve Your Diet",
	"The Power of Gratitude: Why It Matters",
	"How to Land Your Dream Job",
	"Tips for Improving Focus and Concentration",
	"The Art of Setting Achievable Goals",
	"How to Balance Work and Family Life",
	"Top 10 Outdoor Activities for Relaxation",
	"The Role of Creativity in Problem Solving",
	"How to Build a Strong Online Presence",
	"Overcoming Procrastination: A Guide",
	"Why Self-Care Is More Than a Buzzword",
	"The Benefits of Learning a Second Language",
	"How to Organize Your Workspace for Maximum Efficiency",
	"The Best Ways to Celebrate Small Wins",
	"How to Find Inspiration When You're Stuck",
	"The Science of Building Positive Habits",
	"How to Navigate Career Changes Successfully",
	"Simple Ways to Give Back to Your Community",
	"The Impact of Digital Detoxing on Mental Health",
	"How to Cultivate a Growth Mindset",
}

var fakePostsContent = []string{
	"Start your day right with these proven tips for a productive morning routine.",
	"Discover the key steps to successfully launching your own business.",
	"Learn how to stay productive and connected while working remotely.",
	"Explore breathtaking destinations perfect for thrill-seekers and adventurers.",
	"Quick and healthy recipes to fuel your body and mind.",
	"The science behind better sleep and how to achieve it every night.",
	"Step-by-step guide to building habits that stick for a lifetime.",
	"Why learning new skills can transform your career and personal life.",
	"Simple yet effective ways to cut costs without sacrificing quality.",
	"These top apps will keep your life organized and stress-free.",
	"Overcome fear and unlock your true potential with these actionable tips.",
	"An inside look at how artificial intelligence is shaping our future.",
	"Writing a blog? Here's how to captivate your audience and keep them engaged.",
	"Time management tips that will take your productivity to the next level.",
	"Fitness doesn't have to be hard—try these hacks for staying active on a busy schedule.",
	"Practical strategies for boosting your self-confidence and self-esteem.",
	"Learn how minimalism can lead to a more fulfilling and stress-free life.",
	"Networking tips to help you build meaningful professional relationships.",
	"Explore the best books that will inspire your personal growth journey.",
	"Effective communication is a skill—here's how to master it.",
	"Staying motivated while working from home is possible with these strategies.",
	"Combat stress in your everyday life with these simple and proven techniques.",
	"Save time and money with these essential travel hacks.",
	"Starting a podcast is easier than you think—here's everything you need to know.",
	"Master the basics of financial literacy and take control of your finances.",
	"How to create a morning routine that sets you up for a successful day.",
	"Step-by-step guide to planning the ultimate vacation without breaking the bank.",
	"Clear your mind and improve focus with the powerful habit of journaling.",
	"Keep up with the latest technological trends that will shape 2024.",
	"Boost productivity while avoiding burnout with these helpful tips.",
	"Easy diet improvements for better health and wellness.",
	"Discover how practicing gratitude can positively change your outlook on life.",
	"Practical advice on finding and landing your dream job.",
	"Proven techniques for improving your focus and getting more done.",
	"Set achievable goals with this framework to ensure your success.",
	"Work-life balance is crucial—here's how to make it a reality.",
	"Unwind with these relaxing outdoor activities perfect for any season.",
	"Creative problem-solving starts with these simple exercises.",
	"Building a strong online presence is easier than ever—here's how to do it.",
	"Stop procrastinating and start achieving with this practical guide.",
	"Self-care isn't selfish—discover why it matters more than ever.",
	"Unlock opportunities by learning a second language with these tips.",
	"Organize your workspace for better focus and productivity.",
	"Celebrate your wins, big or small, with these simple ideas.",
	"Feeling stuck? Here's how to find inspiration and move forward.",
	"Learn the psychology behind habit formation and how to apply it to your goals.",
	"Change can be scary—here's how to navigate career transitions successfully.",
	"Give back to your community with these easy and impactful actions.",
	"Digital detoxing can improve your mental health—here's how to get started.",
	"Adopt a growth mindset and unlock new opportunities for success.",
}

var fakePostsComments = []string{
	"Great post! Really helpful tips, thank you!",
	"This is exactly what I needed to read today.",
	"I never thought of it that way—very insightful!",
	"Can you elaborate more on this topic? It's fascinating.",
	"Thanks for sharing, I’ll definitely try this out.",
	"Fantastic guide! Your content always stands out.",
	"Do you ha4ve any additional resources on this?",
	"This post just made my day better—thanks!",
	"I’ve been struggling with this; your advice is spot on.",
	"Great work, looking forward to more posts like this!",
	"I love your writing style, it’s so engaging.",
	"This is such a practical and actionable post. Kudos!",
	"I totally agree with your points, well said.",
	"This really resonates with me, thank you for sharing.",
	"Your posts always provide so much value!",
	"I’m sharing this with my friends—this is gold!",
	"Could you share more examples or case studies?",
	"This perspective is new to me, and I love it.",
	"Keep up the great work, your content is inspiring.",
	"I tried this and it worked perfectly. Thanks!",
	"Such a relatable and well-written post!",
	"This is a game-changer. I never knew this before!",
	"Thank you for simplifying a complex topic!",
	"Wow, this is so informative. You nailed it!",
	"Love how detailed this post is. Awesome work!",
	"Any suggestions for beginners starting out?",
	"Interesting take on the subject—I’d like to learn more.",
	"Brilliant advice! I can’t wait to apply this.",
	"This is a must-read for anyone facing similar issues.",
	"Your insights are always on point. Great post!",
	"I appreciate how you broke this down step-by-step.",
	"This is exactly what I needed—thank you so much!",
	"Such a refreshing perspective. Great writing!",
	"I feel motivated after reading this, thanks a ton!",
	"This was so clear and easy to understand.",
	"Do you have any related posts on this topic?",
	"You’re my go-to source for advice. Thanks again!",
	"This deserves way more attention—awesome work!",
	"I love how practical your tips are!",
	"This just inspired me to take action. Thank you!",
	"Solid advice—keep it coming!",
	"I’ve bookmarked this for future reference. Thanks!",
	"This is such a well-researched and thorough post.",
	"Can’t wait to see more posts like this one!",
	"Your content never fails to impress me.",
	"This is exactly what I needed to move forward.",
	"I’m blown away by how much value you packed into this post.",
	"This perspective really made me think. Thank you!",
	"Absolutely love the way you approach this topic.",
	"You’ve explained this so clearly—great job!",
}
